server {

    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    include /etc/nginx/conf.d/cache.conf;

    location = /health {

        access_log off;
        default_type text/plain;

        return 200 "OK\n";

    }

    location / {

        try_files $uri $uri/ /index.html;

    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location = /404.html {
        internal;
    }

    location = /50x.html {
        internal;
    }

}
