# Static Assets
location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {

    expires 30d;

    add_header Cache-Control "public, max-age=2592000, immutable";

    access_log off;

}

# HTML Files
location ~* \.(html)$ {

    expires -1;

    add_header Cache-Control "no-cache";

}
